name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#on:
# push:
#   paths:
#     - '.streamlit/**'
#     - 'Dockerfile-for-github-action'
#     - 'requirements.txt'
#     - 'example.env'
#     - '.github/workflows/docker-image.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        PLATFORMS=linux/amd64
        DOCKER_IMAGE=renhai/streamlit-app
        docker buildx build --platform $PLATFORMS -t $DOCKER_IMAGE:land-latest --file Dockerfile-for-github-action --push .